/**
 * DAR: APP APP HZ
 * Api rest on a task application
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Task { 
    id: number;
    description?: string;
    /**
     * task status
     */
    status?: Task.StatusEnum;
}
export namespace Task {
    export type StatusEnum = 'TO-DO' | 'Work in progess' | 'DONE';
    export const StatusEnum = {
        TODO: 'TO-DO' as StatusEnum,
        WorkInProgess: 'Work in progess' as StatusEnum,
        DONE: 'DONE' as StatusEnum
    };
}
